### ISSUE TITLE
Add dependency update GH action

### ISSUE THREAD

**Issue by fornellas** [fornellas/resonance#21]
Let's add a recurring GH job (eg: weekly) to update all project dependencies:

- It runs `./build.sh go-get-u`, which will update `go.*` files with latest.
- These files must be `git add` and a PR cut with the changes.

This should be done for linux/amd64, as this should be enough to cover all cases.

**Comment by gfechio** [comment]
Let's check how we can use Renovate for that ?

**Comment by gfechio** [comment]
Add to scope: 
- Run Go Vuln Check daily
- Get Go version from go.mod on `input`

**Comment by fornellas** [comment]
Update Go version at `go.mod` on the PR as well.
